INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/800px-Moose_superior.jpg', '1', '1', '8');INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/krokodilas.jpg', '1', '1', '1');INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/png-images-mario-transparent-background-1473.png', '1', '1', '4');INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/talmaciba.jpg', '2', '2', '4');INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/Sarunas_Jasikevicius_by_Augustas_Didzgalvis.jpg', '1', '1', '3');INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/desktop.jpg', '1', '1', '7');INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/krokodilas.jpg', '1', '1', '1');INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/800px-Moose_superior.jpg', '1', '1', '8');INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/desktop.jpg', '1', '1', '2');INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/png-images-mario-transparent-background-1473.png', '1', '1', '4');INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/talmaciba.jpg', '2', '2', '4');INSERT INTO Images (Nuoroda, PageId, ImageID, UserId ) 
        VALUES ('images/Sarunas_Jasikevicius_by_Augustas_Didzgalvis.jpg', '1', '1', '3');